-- ===========================================================================
-- Mod Misc Tool: 复制城邦的图标定义（逐个定义）
--
-- 为什么不用 SQL 批量拉取：图标属于**独立数据库**（IconManager），跟 gameplay 库不互通，
-- 在里面访问不到 Civilizations 表，所以只能把每个复制体的图标逐条写死。
--
-- 数据来源：原版（含资料片、不含 DLC/场景）35 个城邦的 ICON_CIVILIZATION_<文明>，
-- 复制体沿用**同一张图集的同一个位置**（Atlas/Index 照抄），外观与原城邦一致。
-- 复制范围与原版保持一致：本文件同样不设 LoadOrder、由同一个选项判据控制加载。
--
-- Icons 行由 IconDefinitions 的触发器自动建，这里再显式写一遍（OR IGNORE）以防万一。
-- 注意：Index 是 SQLite 保留字，列名必须写成 "Index"（带双引号），否则整条语句语法错误。
-- ===========================================================================

INSERT OR IGNORE INTO Icons (Name) VALUES
  ('ICON_CIVILIZATION_AKKAD_GHOST1'),
  ('ICON_CIVILIZATION_AMSTERDAM_GHOST1'),
  ('ICON_CIVILIZATION_ANTIOCH_GHOST1'),
  ('ICON_CIVILIZATION_BABYLON_GHOST1'),
  ('ICON_CIVILIZATION_BOLOGNA_GHOST1'),
  ('ICON_CIVILIZATION_BRUSSELS_GHOST1'),
  ('ICON_CIVILIZATION_BUENOS_AIRES_GHOST1'),
  ('ICON_CIVILIZATION_CAHOKIA_GHOST1'),
  ('ICON_CIVILIZATION_CARDIFF_GHOST1'),
  ('ICON_CIVILIZATION_CARTHAGE_GHOST1'),
  ('ICON_CIVILIZATION_FEZ_GHOST1'),
  ('ICON_CIVILIZATION_GENEVA_GHOST1'),
  ('ICON_CIVILIZATION_HATTUSA_GHOST1'),
  ('ICON_CIVILIZATION_HONG_KONG_GHOST1'),
  ('ICON_CIVILIZATION_JAKARTA_GHOST1'),
  ('ICON_CIVILIZATION_JERUSALEM_GHOST1'),
  ('ICON_CIVILIZATION_KABUL_GHOST1'),
  ('ICON_CIVILIZATION_KANDY_GHOST1'),
  ('ICON_CIVILIZATION_KUMASI_GHOST1'),
  ('ICON_CIVILIZATION_LA_VENTA_GHOST1'),
  ('ICON_CIVILIZATION_LISBON_GHOST1'),
  ('ICON_CIVILIZATION_MEXICO_CITY_GHOST1'),
  ('ICON_CIVILIZATION_MOHENJO_DARO_GHOST1'),
  ('ICON_CIVILIZATION_NAN_MADOL_GHOST1'),
  ('ICON_CIVILIZATION_NAZCA_GHOST1'),
  ('ICON_CIVILIZATION_NGAZARGAMU_GHOST1'),
  ('ICON_CIVILIZATION_PRESLAV_GHOST1'),
  ('ICON_CIVILIZATION_RAPA_NUI_GHOST1'),
  ('ICON_CIVILIZATION_SEOUL_GHOST1'),
  ('ICON_CIVILIZATION_STOCKHOLM_GHOST1'),
  ('ICON_CIVILIZATION_TORONTO_GHOST1'),
  ('ICON_CIVILIZATION_VALLETTA_GHOST1'),
  ('ICON_CIVILIZATION_VILNIUS_GHOST1'),
  ('ICON_CIVILIZATION_YEREVAN_GHOST1'),
  ('ICON_CIVILIZATION_ZANZIBAR_GHOST1');

INSERT OR IGNORE INTO IconDefinitions (Name, Atlas, "Index") VALUES
  ('ICON_CIVILIZATION_AKKAD_GHOST1', 'ICON_ATLAS_EXPANSION_2_CITY_STATES', 0),
  ('ICON_CIVILIZATION_AMSTERDAM_GHOST1', 'ICON_ATLAS_CIVILIZATIONS', 20),
  ('ICON_CIVILIZATION_ANTIOCH_GHOST1', 'ICON_ATLAS_EXPANSION_1_CITY_STATES', 0),
  ('ICON_CIVILIZATION_BABYLON_GHOST1', 'ICON_ATLAS_EXPANSION_1_CITY_STATES', 1),
  ('ICON_CIVILIZATION_BOLOGNA_GHOST1', 'ICON_ATLAS_EXPANSION_2_CITY_STATES', 1),
  ('ICON_CIVILIZATION_BRUSSELS_GHOST1', 'ICON_ATLAS_CIVILIZATIONS', 21),
  ('ICON_CIVILIZATION_BUENOS_AIRES_GHOST1', 'ICON_ATLAS_CIVILIZATIONS', 22),
  ('ICON_CIVILIZATION_CAHOKIA_GHOST1', 'ICON_ATLAS_EXPANSION_2_CITY_STATES', 2),
  ('ICON_CIVILIZATION_CARDIFF_GHOST1', 'ICON_ATLAS_EXPANSION_2_CITY_STATES', 3),
  ('ICON_CIVILIZATION_CARTHAGE_GHOST1', 'ICON_ATLAS_CIVILIZATIONS', 23),
  ('ICON_CIVILIZATION_FEZ_GHOST1', 'ICON_ATLAS_EXPANSION_2_CITY_STATES', 4),
  ('ICON_CIVILIZATION_GENEVA_GHOST1', 'ICON_ATLAS_CIVILIZATIONS', 24),
  ('ICON_CIVILIZATION_HATTUSA_GHOST1', 'ICON_ATLAS_CIVILIZATIONS', 25),
  ('ICON_CIVILIZATION_HONG_KONG_GHOST1', 'ICON_ATLAS_CIVILIZATIONS', 26),
  ('ICON_CIVILIZATION_JAKARTA_GHOST1', 'ICON_ATLAS_CIVILIZATIONS', 27),
  ('ICON_CIVILIZATION_JERUSALEM_GHOST1', 'ICON_ATLAS_CIVILIZATIONS', 28),
  ('ICON_CIVILIZATION_KABUL_GHOST1', 'ICON_ATLAS_CIVILIZATIONS', 29),
  ('ICON_CIVILIZATION_KANDY_GHOST1', 'ICON_ATLAS_CIVILIZATIONS', 30),
  ('ICON_CIVILIZATION_KUMASI_GHOST1', 'ICON_ATLAS_CIVILIZATIONS', 31),
  ('ICON_CIVILIZATION_LA_VENTA_GHOST1', 'ICON_ATLAS_CIVILIZATIONS', 32),
  ('ICON_CIVILIZATION_LISBON_GHOST1', 'ICON_ATLAS_CIVILIZATIONS', 34),
  ('ICON_CIVILIZATION_MEXICO_CITY_GHOST1', 'ICON_ATLAS_EXPANSION_2_CITY_STATES', 5),
  ('ICON_CIVILIZATION_MOHENJO_DARO_GHOST1', 'ICON_ATLAS_CIVILIZATIONS', 35),
  ('ICON_CIVILIZATION_NAN_MADOL_GHOST1', 'ICON_ATLAS_CIVILIZATIONS', 36),
  ('ICON_CIVILIZATION_NAZCA_GHOST1', 'ICON_ATLAS_EXPANSION_2_CITY_STATES', 6),
  ('ICON_CIVILIZATION_NGAZARGAMU_GHOST1', 'ICON_ATLAS_EXPANSION_2_CITY_STATES', 7),
  ('ICON_CIVILIZATION_PRESLAV_GHOST1', 'ICON_ATLAS_CIVILIZATIONS', 37),
  ('ICON_CIVILIZATION_RAPA_NUI_GHOST1', 'ICON_ATLAS_EXPANSION_2_CITY_STATES', 8),
  ('ICON_CIVILIZATION_SEOUL_GHOST1', 'ICON_ATLAS_CIVILIZATIONS', 38),
  ('ICON_CIVILIZATION_STOCKHOLM_GHOST1', 'ICON_ATLAS_CIVILIZATIONS', 39),
  ('ICON_CIVILIZATION_TORONTO_GHOST1', 'ICON_ATLAS_CIVILIZATIONS', 40),
  ('ICON_CIVILIZATION_VALLETTA_GHOST1', 'ICON_ATLAS_CIVILIZATIONS', 41),
  ('ICON_CIVILIZATION_VILNIUS_GHOST1', 'ICON_ATLAS_CIVILIZATIONS', 42),
  ('ICON_CIVILIZATION_YEREVAN_GHOST1', 'ICON_ATLAS_CIVILIZATIONS', 33),
  ('ICON_CIVILIZATION_ZANZIBAR_GHOST1', 'ICON_ATLAS_CIVILIZATIONS', 43);
